version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  # command-handler:
  #   image: localhost:5000/command-handler:latest
  #   build:
  #     context: .
  #     container_name: command-handler
  #     dockerfile: containers/CommandHandler.Dockerfile

  # query-handler:
  #   image: localhost:5000/query-handler:latest
  #   build:
  #     context: .
  #     container_name: query-handler
  #     dockerfile: containers/QueryHandler.Dockerfile

  # command-proxy:
  #   image: localhost:5000/command-proxy:latest
  #   build:
  #     context: .
  #     container_name: command-proxy
  #     dockerfile: containers/CommandProxy.Dockerfile

  # query-proxy:
  #   image: localhost:5000/query-proxy:latest
  #   build:
  #     context: .
  #     container_name: query-proxy
  #     dockerfile: containers/QueryProxy.Dockerfile

  # gateway:
  #   image: localhost:5000/gateway:latest
  #   build:
  #     context: .
  #     dockerfile: containers/Gateway.Dockerfile