apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "todo.selectorLabels" . | nindent 6 }}
  template:
      labels:
        {{- include "todo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.commandhandler.repository }}:{{ .Values.commandhandler.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: TCP
              containerPort: 5000
              protocol: TCP